// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure.

  // Sidebar for 'Home'.

  // Sidebar for Docs
  docsSidebar: [{ type: "autogenerated", dirName: "docs" }],

  // Sidebar for API
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
